### ISSUE TITLE
Could not pass event PluginEnableEvent to ForgeRestrictor v1.4-DEV-8

### ISSUE THREAD

**Issue by EduardoMGP** [KaiKikuchi/ForgeRestrictor#28]
Hi, could you help me?
I have a problem in the plugin.
but it works normal
although sometimes bugar a chunk
and not allow the owner to put cables
of applied energistics
thank you

`[21:23:06] [Server thread/ERROR]: Could not pass event PluginEnableEvent to ForgeRestrictor v1.4-DEV-8
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.57]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.57]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.57]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:375) [JavaPluginLoader.class:1.7.10-1614.57]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.57]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.57]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.57]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/association/RegionAssociable
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_91]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_91]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_91]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_91]
	at net.kaikk.mc.fr.ProtectionPlugins.createHandler(ProtectionPlugins.java:32) ~[?:?]
	at net.kaikk.mc.fr.EventListener.pluginEnable(EventListener.java:227) ~[?:?]
	at net.kaikk.mc.fr.EventListener.onPluginEnable(EventListener.java:213) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
	... 13 more`

**Comment by spannerman79** [comment]
>  `java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/association/RegionAssociable`

Prob too high of a version of worldguard https://github.com/KaiKikuchi/ForgeRestrictor/blob/master/pom.xml#L73

**Comment by EduardoMGP** [comment]
that's it
I'm using version 5.9
Any more problems or can I leave it?
Will not Delay Server Delay?
for I have another plugin also that only works in version 6 down of the worldguard

**Comment by spannerman79** [comment]
That is the problem - the version of worldguard your using is too low.

Look at the link I gave before - worldguard 6.0

**Comment by KaiKikuchi** [comment]
Indeed WorldGuard v6.0 is required

**Comment by KaneHart** [comment]
Sorry but where can I get WG 6.0 there was beta and then 6.1 but no 6.0 snapshot from their bukkit page.
